services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/code_learning_db
      - SECRET_KEY=your_secret_key
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=code_learning_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  upload_data:
